services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: codespaces-sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlServer@12345"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

    restart: unless-stopped

  mysql:
    image: mysql:8.4
    container_name: mysql-pyspark
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_db
      MYSQL_USER: sparkuser
      MYSQL_PASSWORD: sparkpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:17
    container_name: postgres-pyspark
    restart: unless-stopped
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: sparkuser
      POSTGRES_PASSWORD: sparkpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  sqlserver_data:
  mysql_data:
  postgres_data: